apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    alerts.k8s.io/KubePersistentVolumeFillingUp: disabled
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.20.8
    instancetype.kubevirt.io/default-instancetype: u1.medium
    instancetype.kubevirt.io/default-preference: fedora
    kubevirt.io/created-by: 80406ec4-dac1-4b9f-b784-c88d6e9fec76
  name: fedora-teal-peacock-33
  namespace: vmtocloud
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: '34144990004'
  storageClassName: democratic-csi-nfs
  volumeMode: Filesystem

